export const GET_JOBSITES = "GET_JOB_SITES";
export const GET_JOBSITES_SUCCESS = "GET_JOB_SITES_SUCCESS";
export const GET_JOBSITES_FAIL = "GET_JOB_SITES_FAIL";

export const ADD_JOBSITE = "ADD_JOBSITE";
export const ADD_JOBSITE_SUCCESS = "ADD_JOBSITE_SUCCESS";
export const ADD_JOBSITE_FAIL = "ADD_JOBSITE_FAIL";

export const TOGGLE_ADD_JOBSITE_MODAL = "TOGGLE_ADD_JOBSITE_MODAL";
