export const TOGGLE_ADD_JOBSITE_MODAL = "TOGGLE_ADD_JOBSITE_MODAL";
export const TOGGLE_DELETE_JOBSITE_MODAL = "TOGGLE_DELETE_JOBSITE_MODAL";
export const TOGGLE_ADD_CATEGORY_MODAL = "TOGGLE_ADD_CATEGORY_MODAL";
